<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<div class="blog-post-list">
    <h1><?= __('Blog posts') ?></h1>
    <ul>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 1]) ?>>"> Panda1</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 2]) ?>>"> Panda2</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 3]) ?>>"> Panda3</a></li>

    </ul>
    <p><?=__('Post count: %1', 3)?></p>
</div>
