<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<div class="blog-post-sidebar">
    <p><strong><?= __('Other blog posts') ?></strong></p>
    <ul>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 1]) ?>>"> Panda1</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 2]) ?>>"> Panda2</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 3]) ?>>"> Panda3</a></li>

    </ul>
</div>
